### ISSUE TITLE
Roundcube: Invalid request! No data was saved.

### ISSUE THREAD

**Issue by lespinosa** [zpanel/installers#12] opened 2014-03-04 16:38 UTC
when an update to php 5.4 is done using the ZPanel-php54-release package, rouncube not working leaves and get the following error:  Invalid request! No data was saved.
this happens when I try to log in.

zPanel version 10.1.1

**Comment by ghost** [comment] 2014-03-14 22:55
Please read the install requirement. PHP 5.4 is not currently officially supported by Zpanel even if we are testing it and it works.

If you customize zpanel and go beyond the recommended stack you can't call for bugs here and may likely break zpanel security model. Check Zpanel forum this has been discussed before.

**Comment by ghost** [comment] 2014-05-12 07:22
Closing. USE THE FORUMS FOR SUPPORT.

This is not a bug not an issue and the support team will be happy to reply @:

http://forums.zpanelcp.com/

THANKS

**Closed as completed by ghost** 2014-05-12 07:22 UTC
